# Tomcat
server:
    tomcat:
        uri-encoding: UTF-8
        max-threads: 1000
        min-spare-threads: 30
    port: 8088
    connection-timeout: 5000
    context-path: /BSCrawler

spring:
    # 环境 dev|test|pro
    profiles:
        active: dev
    # jackson时间格式化
    jackson:
        time-zone: GMT+8
        date-format: yyyy-MM-dd HH:mm:ss
    data:
        mongodb:
            host: 127.0.0.1
            port: 27017
            database: crawler
    http:
        multipart:
            max-file-size: 100MB
            max-request-size: 100MB
            enabled: true
    resources: # 指定静态资源的路径
        static-locations: classpath:/static/,classpath:/views/
    redis:
        open: false  # 是否开启redis缓存  true开启   false关闭
        database: 0
        host: redis.open.renren.io
        port: 16379
        password:       # 密码（默认为空）
        timeout: 6000  # 连接超时时长（毫秒）
        pool:
            max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
            max-wait: -1      # 连接池最大阻塞等待时间（使用负值表示没有限制）
            max-idle: 10      # 连接池中的最大空闲连接
            min-idle: 5       # 连接池中的最小空闲连接

# Mybatis配置
mybatis:
    mapperLocations: classpath:mapper/**/*.xml
    configuration:
        mapUnderscoreToCamelCase: true
        callSettersOnNulls: true
        jdbcTypeForNull: NULL
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 采集的微信的 pdf 文件的存放的位置
crawler:
    weixin:
         pdf:
             path: data/webmagic/weixin.sogou.com
    news:
         content:
             similarity:
                  factor: 0.8
         image:
             nginx:
#                  rootpath: http://47.105.60.166:10010/imgs
                  rootpath: http://127.0.0.1:80/webmagic

         blacklist:

# casperjs 的存放的位置
casperjs:
  exe:
     path: D:/data/webmagic/

classify:
    modelpath: svm-classification-model.ser

ftp:
    server:
        url: 127.0.0.1
        port: 2121
        username: admin
        password: admin
        path: E:/tmp


casper:
    js:
      exe:
            path: D:/data/webmagic/

